copy /Y Nu_Link_Driver.ini D:\MCU\FC8243\BSPv3\SampleCode\Hard_Fault_Sample\Keil\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FC8243\BSPv3\SampleCode\M051-LB_004\ADC_PWM\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FC8243\BSPv3\SampleCode\M051-LB_004\Capture\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FC8243\BSPv3\SampleCode\M051-LB_004\DeepSleep\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FC8243\BSPv3\SampleCode\M051-LB_004\FMC\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FC8243\BSPv3\SampleCode\M051-LB_004\I2C_24LC64\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FC8243\BSPv3\SampleCode\M051-LB_004\I2C_Software_GPIO\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FC8243\BSPv3\SampleCode\M051-LB_004\I2C_Software_GPIO_Timer\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FC8243\BSPv3\SampleCode\M051-LB_004\Idle\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FC8243\BSPv3\SampleCode\M051-LB_004\Interrupt\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FC8243\BSPv3\SampleCode\M051-LB_004\SPI_Flash_Without_FIFO\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FC8243\BSPv3\SampleCode\M051-LB_004\SPI_Flash_With_FIFO\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FC8243\BSPv3\SampleCode\M051-LB_004\StartKit\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FC8243\BSPv3\SampleCode\RegBased\ACMP\Keil\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FC8243\BSPv3\SampleCode\RegBased\ACMP_Wakeup\Keil\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FC8243\BSPv3\SampleCode\RegBased\ADC_BurstMode\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FC8243\BSPv3\SampleCode\RegBased\ADC_ContinuousScanMode\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FC8243\BSPv3\SampleCode\RegBased\ADC_PwmTrigger\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FC8243\BSPv3\SampleCode\RegBased\ADC_ResultMonitor\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FC8243\BSPv3\SampleCode\RegBased\ADC_SingleCycleScanMode\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FC8243\BSPv3\SampleCode\RegBased\ADC_SingleMode\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FC8243\BSPv3\SampleCode\RegBased\EBI_NOR\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FC8243\BSPv3\SampleCode\RegBased\EBI_SRAM\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FC8243\BSPv3\SampleCode\RegBased\FMC_IAP\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FC8243\BSPv3\SampleCode\RegBased\FMC_MultiBoot\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FC8243\BSPv3\SampleCode\RegBased\FMC_MultiBoot_SwReset\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FC8243\BSPv3\SampleCode\RegBased\FMC_RW\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FC8243\BSPv3\SampleCode\RegBased\GPIO_EINTAndDebounce\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FC8243\BSPv3\SampleCode\RegBased\GPIO_INT\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FC8243\BSPv3\SampleCode\RegBased\GPIO_OutputInput\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FC8243\BSPv3\SampleCode\RegBased\GPIO_PowerDown\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FC8243\BSPv3\SampleCode\RegBased\HDIV\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FC8243\BSPv3\SampleCode\RegBased\I2C_EEPROM\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FC8243\BSPv3\SampleCode\RegBased\I2C_GCMode_Master\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FC8243\BSPv3\SampleCode\RegBased\I2C_GCMode_Slave\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FC8243\BSPv3\SampleCode\RegBased\I2C_Master\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FC8243\BSPv3\SampleCode\RegBased\I2C_Slave\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FC8243\BSPv3\SampleCode\RegBased\I2C_Wakeup_Master\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FC8243\BSPv3\SampleCode\RegBased\I2C_Wakeup_Slave\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FC8243\BSPv3\SampleCode\RegBased\PWM\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FC8243\BSPv3\SampleCode\RegBased\PWM_Capture\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FC8243\BSPv3\SampleCode\RegBased\PWM_DeadZone\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FC8243\BSPv3\SampleCode\RegBased\PWM_DoubleBuffer\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FC8243\BSPv3\SampleCode\RegBased\SPI_Loopback\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FC8243\BSPv3\SampleCode\RegBased\SPI_MasterFifoMode\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FC8243\BSPv3\SampleCode\RegBased\SPI_SlaveFifoMode\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FC8243\BSPv3\SampleCode\RegBased\SYS\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FC8243\BSPv3\SampleCode\RegBased\TIMER_Capture\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FC8243\BSPv3\SampleCode\RegBased\TIMER_Counter\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FC8243\BSPv3\SampleCode\RegBased\TIMER_PeriodicINT\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FC8243\BSPv3\SampleCode\RegBased\TIMER_PowerDown\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FC8243\BSPv3\SampleCode\RegBased\UART_Autoflow_Master\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FC8243\BSPv3\SampleCode\RegBased\UART_Autoflow_Slave\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FC8243\BSPv3\SampleCode\RegBased\UART_IrDA_Master\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FC8243\BSPv3\SampleCode\RegBased\UART_IrDA_Slave\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FC8243\BSPv3\SampleCode\RegBased\UART_LIN\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FC8243\BSPv3\SampleCode\RegBased\UART_RS485_Master\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FC8243\BSPv3\SampleCode\RegBased\UART_RS485_Slave\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FC8243\BSPv3\SampleCode\RegBased\UART_TxRx_Function\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FC8243\BSPv3\SampleCode\RegBased\UART_Wakeup\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FC8243\BSPv3\SampleCode\RegBased\WDT_PowerDown\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FC8243\BSPv3\SampleCode\RegBased\WDT_TimeoutINT\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FC8243\BSPv3\SampleCode\RegBased\WDT_TimeoutReset\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FC8243\BSPv3\SampleCode\RegBased\WWDT_CompareINT\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FC8243\BSPv3\SampleCode\Semihost\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FC8243\BSPv3\SampleCode\StdDriver\ACMP\Keil\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FC8243\BSPv3\SampleCode\StdDriver\ACMP_Wakeup\Keil\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FC8243\BSPv3\SampleCode\StdDriver\ADC_BurstMode\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FC8243\BSPv3\SampleCode\StdDriver\ADC_ContinuousScanMode\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FC8243\BSPv3\SampleCode\StdDriver\ADC_PwmTrigger\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FC8243\BSPv3\SampleCode\StdDriver\ADC_ResultMonitor\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FC8243\BSPv3\SampleCode\StdDriver\ADC_SingleCycleScanMode\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FC8243\BSPv3\SampleCode\StdDriver\ADC_SingleMode\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FC8243\BSPv3\SampleCode\StdDriver\EBI_NOR\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FC8243\BSPv3\SampleCode\StdDriver\EBI_SRAM\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FC8243\BSPv3\SampleCode\StdDriver\FMC_IAP\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FC8243\BSPv3\SampleCode\StdDriver\FMC_RW\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FC8243\BSPv3\SampleCode\StdDriver\GPIO_EINTAndDebounce\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FC8243\BSPv3\SampleCode\StdDriver\GPIO_INT\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FC8243\BSPv3\SampleCode\StdDriver\GPIO_OutputInput\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FC8243\BSPv3\SampleCode\StdDriver\GPIO_PowerDown\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FC8243\BSPv3\SampleCode\StdDriver\HDIV\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FC8243\BSPv3\SampleCode\StdDriver\I2C_EEPROM\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FC8243\BSPv3\SampleCode\StdDriver\I2C_GCMode_Master\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FC8243\BSPv3\SampleCode\StdDriver\I2C_GCMode_Slave\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FC8243\BSPv3\SampleCode\StdDriver\I2C_Master\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FC8243\BSPv3\SampleCode\StdDriver\I2C_Slave\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FC8243\BSPv3\SampleCode\StdDriver\I2C_Wakeup_Master\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FC8243\BSPv3\SampleCode\StdDriver\I2C_Wakeup_Slave\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FC8243\BSPv3\SampleCode\StdDriver\PWM\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FC8243\BSPv3\SampleCode\StdDriver\PWM_Capture\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FC8243\BSPv3\SampleCode\StdDriver\PWM_DeadZone\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FC8243\BSPv3\SampleCode\StdDriver\PWM_DoubleBuffer\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FC8243\BSPv3\SampleCode\StdDriver\SPI_Loopback\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FC8243\BSPv3\SampleCode\StdDriver\SPI_MasterFifoMode\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FC8243\BSPv3\SampleCode\StdDriver\SPI_SlaveFifoMode\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FC8243\BSPv3\SampleCode\StdDriver\SYS\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FC8243\BSPv3\SampleCode\StdDriver\TIMER_Capture\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FC8243\BSPv3\SampleCode\StdDriver\TIMER_Counter\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FC8243\BSPv3\SampleCode\StdDriver\TIMER_PeriodicINT\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FC8243\BSPv3\SampleCode\StdDriver\TIMER_PowerDown\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FC8243\BSPv3\SampleCode\StdDriver\UART_Autoflow_Master\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FC8243\BSPv3\SampleCode\StdDriver\UART_Autoflow_Slave\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FC8243\BSPv3\SampleCode\StdDriver\UART_IrDA_Master\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FC8243\BSPv3\SampleCode\StdDriver\UART_IrDA_Slave\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FC8243\BSPv3\SampleCode\StdDriver\UART_LIN\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FC8243\BSPv3\SampleCode\StdDriver\UART_RS485_Master\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FC8243\BSPv3\SampleCode\StdDriver\UART_RS485_Slave\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FC8243\BSPv3\SampleCode\StdDriver\UART_TxRx_Function\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FC8243\BSPv3\SampleCode\StdDriver\UART_Wakeup\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FC8243\BSPv3\SampleCode\StdDriver\WDT_PowerDown\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FC8243\BSPv3\SampleCode\StdDriver\WDT_TimeoutINT\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FC8243\BSPv3\SampleCode\StdDriver\WDT_TimeoutReset\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FC8243\BSPv3\SampleCode\StdDriver\WWDT_CompareINT\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FC8243\BSPv3\SampleCode\Template\Keil\Nu_Link_Driver.ini
